### ISSUE TITLE
Document damage control module

### ISSUE THREAD

**Issue by jorgeberrex** [WarzoneMC/Docs#12]
```JSON
"damageControl": {
   "fire": false,
   "suffocation": false,
   "fall": false
}
```

[DamageControlModule.java](https://github.com/WarzoneMC/Warzone/blob/master/TGM/src/main/java/network/warzone/tgm/modules/damage/DamageControlModule.java)

**Comment by Palmidence** [comment]
Documented

**Comment by jorgeberrex** [comment]
the DamageControlModule has been updated to control any kind of damage. New format:

```JSON
"damageControl": {
   "BLOCK_EXPLOSION": false,
   "PROJECTILE": false,
   "SUFFOCATION": false
}
```

[A list of all the damage causes](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/entity/EntityDamageEvent.DamageCause.html)

**Comment by BennyDoesTheStuff** [comment]
Would we be able to use lowercase and spaces like "block explosion": false

**Comment by jorgeberrex** [comment]
Yes

**Comment by Palmidence** [comment]
Duck Fermentation

**Comment by Palmidence** [comment]
> Duck Fermentation

Documented*
